language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    include:
        # Test against Symfony stable versions
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
        # Test against dev versions
        - php: 5.6
          env: DEPENDENCIES=dev
    allow_failures:
        - php: hhvm
        - env: DEPENDENCIES=dev

install:
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - composer update $COMPOSER_FLAGS

script: phpunit -v
